development:
  adapter: sqlite3
  database: db/development.sqlite3
    # 
    # adapter: mysql2
    # encoding: utf8
  reconnect: false
  database: monologue_development
  pool: 5
  username: root
  password:

test:
  adapter: sqlite3
  database: db/development.sqlite3

  # adapter: mysql2
  # encoding: utf8
  reconnect: false
  database: monologue_test
  pool: 5
  username: root
  password: